fox:
  sticker:
    input-path: "C:/Users/72409/OneDrive/Desktop/狐瓜西/images_png"   # 改这里
    output-path: "C:/Users/72409/OneDrive/Desktop/狐瓜西/test" # 改这里
    # 目标尺寸
    width: 512
    height: 512
    # 警告：除非你有14900K以及64G内存，请勿设置过高的并发。
    parallelism: 128

logging:
  level:
    root: INFO
    com.foxsoftware: INFO